filetype plugin indent on
set nolist
" Disable intro message
set shortmess=I
set encoding=UTF-8
set nobackup
set noswapfile
" enable folding
set foldenable
" Open most folds by default
set foldlevelstart=32
" Sets the fold type to indentation
set foldmethod=indent
set number
set ruler
set mouse=a
set nocompatible
syntax on
set wrap
set pastetoggle=<F2>
set encoding=utf8
set termencoding=utf-8
set backspace=indent,eol,start
" Sets number of spaces in each tab representation
set tabstop=2
" Sets number of spaces actually in each tab
set softtabstop=2
set smarttab
set shiftwidth=2
set autoindent
set smartindent
set shiftround
" Change all tabs to spaces
set expandtab
set ignorecase
" visual autocomplete for command menu
set wildmenu
set smartcase
set relativenumber
" search as you type
set incsearch           
" highlight searches
set hlsearch           
set autoread
" Prevent wasteful redraws
set lazyredraw
nnoremap <F4> :set relativenumber!<CR>
" Always display the status line on the bottom window only
set laststatus=1
" open a new buffer without saving current changed buffers
set hidden
" Make vim use system clipboard
" TODO make this cross platform
set clipboard=unnamed,unnamedplus
let mapleader = "\<Space>"
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" reload vimrc after editing
" This is a really good idea, but seems to break airline/devicons
" Also may be causing memory leak
if has("autocmd")
  "autocmd bufwritepost .vimrc source $MYVIMRC
  "autocmd bufwritepost vimrc source $MYVIMRC
endif

" shortcut to edit this file in new window
nmap <leader>v :vsp $MYVIMRC<CR>

" Trigger updates
au FocusGained,BufEnter * :checktime
au CursorHold,CursorHoldI * checktime

call plug#begin('~/.vim/plugged')
Plug 'Valloric/YouCompleteMe', { 'do': './install.py --tern-completer' }
" FocusGained and FocusLost autocommand events are not working in terminal vim. 
" This plugin restores them when using vim inside Tmux.
Plug 'tmux-plugins/vim-tmux-focus-events'
" Live markdown previewing
Plug 'shime/vim-livedown'
" Icons for NerdTree
Plug 'ryanoasis/vim-devicons'
Plug 'xolox/vim-easytags'
Plug 'xolox/vim-misc'
Plug 'majutsushi/tagbar'
Plug 'lervag/vimtex'
" Easily repeat non-native commands
Plug 'tpope/vim-repeat'
" Change clipboard behavior to be more sane
Plug 'svermeulen/vim-easyclip'
" Insert or delete brackets, parens, quotes in pairs
Plug 'jiangmiao/auto-pairs'
" Auto close *ML tags
Plug 'alvan/vim-closetag/'
" Sort Typescript imports
Plug 'ruanyl/vim-sort-imports'
" Superb status line
Plug 'vim-airline/vim-airline'
" Styles for airline
Plug 'vim-airline/vim-airline-themes'
" Real time interpreter
" start with :Codi
Plug 'metakirby5/codi.vim'
Plug 'farmergreg/vim-lastplace'
Plug 'scrooloose/nerdcommenter'
" <leader>p or :Prettier
Plug 'prettier/vim-prettier', {
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue'] }
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" Highlight patterns for EX commands
Plug 'markonm/traces.vim'
" Color schemes
Plug 'trevordmiller/nova-vim'
Plug 'danilo-augusto/vim-afterglow'
" visual indentation
Plug 'Yggdroot/indentLine'
Plug 'mattn/emmet-vim'
" transition between multi and single line code
" gS to split into multiple lines
" gJ to join into a single line
Plug 'andrewradev/splitjoin.vim'

" Typescript Plugins
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
Plug 'Quramy/tsuquyomi', { 'do': 'npm install -g typescript' }
Plug 'leafgarland/typescript-vim'

" Go
Plug 'fatih/vim-go', { 'for': 'go' }
Plug 'jodosha/vim-godebug', { 'for': 'go' }
Plug 'tpope/vim-surround'

" Fill in jsdoc with :JsDoc
Plug 'heavenshell/vim-jsdoc'
Plug 'jeetsukumaran/vim-buffergator'
" Git wrapper
" :Gdiff
Plug 'tpope/vim-fugitive'
" Integrates vim-fugitive with hub
Plug 'tpope/vim-rhubarb'
" visually select some text and begin
" aligning with <ga>
Plug 'junegunn/vim-easy-align'
" Linter/fixer
Plug 'w0rp/ale'
" Very nice git log viewer
" :Agit
Plug 'cohama/agit.vim'
" Show git changes in the gutter
Plug 'mhinz/vim-signify'
" Alternate bracket coloring
Plug 'eapache/rainbow_parentheses.vim'
" Ranger in vim 
Plug 'francoiscabrol/ranger.vim'
" Clojure stuff
" Connect to lein repl
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }
Plug 'guns/vim-sexp', { 'for': 'clojure' }
Plug 'tpope/vim-sexp-mappings-for-regular-people', { 'for': 'clojure' }

" Syntax
Plug 'sheerun/vim-polyglot'
call plug#end()

" Disable JSON conceallevel
augroup jsonConceal
  au!
  au FileType json set conceallevel=0
augroup end

" Enable hard wrapping for certain filetypes
augroup wrapping
  au!
  au FileType markdown set tw=79
augroup end

" for rainbow_parentheses
let g:rbpt_colorpairs = [
      \ ['brown',       'RoyalBlue3'],
      \ ['Darkblue',    'SeaGreen3'],
      \ ['darkgray',    'DarkOrchid3'],
      \ ['darkgreen',   'firebrick3'],
      \ ['darkcyan',    'RoyalBlue3'],
      \ ['darkred',     'SeaGreen3'],
      \ ['darkmagenta', 'DarkOrchid3'],
      \ ['brown',       'firebrick3'],
      \ ['gray',        'RoyalBlue3'],
      \ ['black',       'SeaGreen3'],
      \ ['darkmagenta', 'DarkOrchid3'],
      \ ['Darkblue',    'firebrick3'],
      \ ['darkgreen',   'RoyalBlue3'],
      \ ['darkcyan',    'SeaGreen3'],
      \ ['darkred',     'DarkOrchid3'],
      \ ['red',         'firebrick3'],
      \ ]

" load raindow_parentheses by default
let g:rbpt_loadcmd_toggle = 1

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

let g:ranger_map_keys = 0
" nerdtree-git
let g:NERDTreeIndicatorMapCustom = {
      \ "Modified"  : "✹",
      \ "Staged"    : "✚",
      \ "Untracked" : "✭",
      \ "Renamed"   : "➜",
      \ "Unmerged"  : "═",
      \ "Deleted"   : "✖",
      \ "Dirty"     : "✗",
      \ "Clean"     : "✔︎",
      \ 'Ignored'   : '☒',
      \ "Unknown"   : "?"
      \ }

let NERDTreeQuitOnOpen       = 1
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeMinimalUI        = 1
let NERDTreeDirArrows        = 1

" airline
let g:airline_theme = 'minimalist'
let g:airline#extensions#tabline#enabled     = 1
let g:airline#extensions#tabline#tab_nr_type = 1
let g:airline_powerline_fonts                = 1

" remove ugly triangles
let g:airline_right_sep = ' '
let g:airline_right_alt_sep = '|'
let g:airline_left_sep = ' '
let g:airline_left_alt_sep = '|'
" change the way filepaths are shown in status and tabs
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'

" Enable cursor line position tracking:
set cursorline
" Remove the underline from enabling cursorline:
highlight clear CursorLine
" Set line numbering black on white
highlight CursorLineNR ctermbg=white ctermfg=black

"let $FZF_DEFAULT_COMMAND = 'ag -g "'
let g:fzf_colors =
      \ { 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Comment'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Statement'],
      \ 'info':    ['fg', 'PreProc'],
      \ 'prompt':  ['fg', 'Conditional'],
      \ 'pointer': ['fg', 'Exception'],
      \ 'marker':  ['fg', 'Keyword'],
      \ 'spinner': ['fg', 'Label'],
      \ 'header':  ['fg', 'Comment'] }

nnoremap <silent> <leader><space> :Files<CR>
nnoremap <silent> <leader>a :Buffers<CR>

" fix some annoying stuff
nnoremap <F1> <nop>
nnoremap Q <nop>

" insert new line in normal mode
map <Enter> o<ESC>

map <S-Enter> O<ESC>
" No more escape key!!
nnoremap <C-space> a
imap <C-space> <Esc>
vmap <C-space> <Esc>

nnoremap <C-k> :bnext<CR>
nnoremap <C-j> :bprev<CR>
" nnoremap <C-w> :bd<CR>
" require jsx for files with js plugin
let g:jsx_ext_required = 0
let g:ale_change_sign_column_color = 1
let g:ale_sign_column_always = 1
let g:ale_change_sign_column_color  = 0
inoremap <C-e> <C-o>$
inoremap <C-f> <C-o>^

nmap <F8> :TagbarToggle<CR>

" NERDTress File highlighting
function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
  exec 'autocmd FileType nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
  exec 'autocmd FileType nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction

call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')
call NERDTreeHighlightFile('ini', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', '#151515')
call NERDTreeHighlightFile('yml', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('config', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('conf', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('html', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', '#151515')
call NERDTreeHighlightFile('js', 'Red', 'none', '#ffa500', '#151515')
call NERDTreeHighlightFile('php', 'Magenta', 'none', '#ff00ff', '#151515')
call NERDTreeHighlightFile('ds_store', 'Gray', 'none', '#686868', '#151515')
call NERDTreeHighlightFile('gitconfig', 'Gray', 'none', '#686868', '#151515')
call NERDTreeHighlightFile('gitignore', 'Gray', 'none', '#686868', '#151515')
call NERDTreeHighlightFile('bashrc', 'Gray', 'none', '#686868', '#151515')
call NERDTreeHighlightFile('bashprofile', 'Gray', 'none', '#686868', '#151515')
call NERDTreeHighlightFile('cs', 'Blue', 'none', 'Blue', '#151515')

" Key command to reload Clojure file in REPL
au Filetype clojure nmap <c-c><c-c> :Require<cr>
au Filetype clojure let g:AutoPairs = {'(':')', '[':']', '{':'}','"':'"', '`':'`'}

nnoremap ; :
vnoremap ; :
nnoremap : ;
vnoremap : ;

" integer value [0|1]
" This will make the list of non-closing tags case-sensitive (e.g. `<Link>` will be closed while `<link>` won't.)
let g:closetag_emptyTags_caseSensitive = 1

" Shortcut for closing tags, default is '>'
let g:closetag_shortcut = '>'

" Add > at current position without closing the current tag, default is ''
let g:closetag_close_shortcut = '<leader>>'

" vim-easy-align mapping
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Stop auto-pairs from moving to next line
let g:AutoPairsMultilineClose = 0

" Disable visual indentation for JSON files (to keep quotes)
let g:indentLine_fileTypeExclude = ['json', 'markdown']
" Start autocompletion after 4 chars
let g:ycm_min_num_of_chars_for_completion = 3
let g:ycm_min_num_identifier_candidate_chars = 4
let g:ycm_enable_diagnostic_highlighting = 0

" Don't show YCM's preview window [ I find it really annoying ]
set completeopt-=preview
let g:ycm_add_preview_to_completeopt = 0

nnoremap gm m

let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.php,*.jsx,*.js"

" Show syntax highlighting groups for word under cursor
nmap <C-S-P> :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

" Some pretty stuff
" highlight Comment cterm=talic

nnoremap <Leader>p :ALEFix<CR>
let g:ale_linters = {}
let g:ale_linters['typescript'] = ['tsserver', 'tslint']
let g:ale_fixers = {}
let g:ale_fixers['javascript'] = ['prettier']
let g:ale_fixers['typescript'] = ['prettier']
let g:ale_fixers['json'] = ['prettier']
let g:ale_fixers['python'] =  ['black']
let g:ale_fixers['sh'] =  ['shfmt']

" turn off search highlight
nnoremap <leader>n :nohlsearch<CR>
" space open/closes folds
"nnoremap <space> za

" highlight last inserted text
nnoremap gV `[v`]

let g:javascript_plugin_flow = 1
map <leader>r :Ranger<CR>
nnoremap <Leader>f :NERDTreeToggle<Enter>

highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

nnoremap <silent> n n:call HLNext(0.4)<cr>
nnoremap <silent> N N:call HLNext(0.4)<cr>

function! HLNext (blinktime)
  set invcursorline
  redraw
  exec 'sleep ' . float2nr(a:blinktime * 1000) . 'm'
  set invcursorline
  redraw
endfunction

if !exists("g:ycm_semantic_triggers")
  let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers['typescript'] = ['.']
