# Setting PATH for Python 3.4
# The orginal version is saved in .zprofile.pysave
if [ "$_SKIP_PROFILE" ]; then
    return 0
else
    export _SKIP_PROFILE=y
fi

source ~/.zpath
export ANDROID_HOME=/usr/local/share/android-sdk
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
