# Skip all this for non-interactive shells
[[ -z "$PS1" ]] && return

export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/.dotFiles
if [[ "$(which vim)" ]]; then
  export EDITOR="vim"
else
  export EDITOR="vi"
fi

ZSH_THEME="spaceship"

SPACESHIP_PROMPT_ADD_NEWLINE="true"
SPACESHIP_CHAR_SYMBOL=" \ue27a"
SPACESHIP_CHAR_PREFIX="\ue231"
SPACESHIP_CHAR_SUFFIX=(" ")
SPACESHIP_CHAR_COLOR_SUCCESS="yellow"
SPACESHIP_PROMPT_DEFAULT_PREFIX="$USER"
SPACESHIP_USER_SHOW=”true”

plugins=(
  git
  brew
  npm
  docker
  zsh-syntax-highlighting
)

# This disables marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

source $ZSH/oh-my-zsh.sh

alias ls="ls -al"
####Package managers####
alias nis="npm install --save"
alias nid="npm install --save-dev"
alias snig="sudo npm install -g"
alias sudo='sudo '
alias git="hub"

bindkey '^N' clear-screen


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_DEFAULT_COMMAND='ag --nocolor --ignore node_modules -g ""'

# TODO https://github.com/MicahElliott/dotfiles/blob/master/config/zshrc
source $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

if [[  -z "$SKIP_PROFILE" ]]; then
  source ~/.zprofile
fi
